export { default as About } from "./About";
export { default as Cart } from "./Cart";
export { default as Checkout } from "./Checkout";
export { default as Home } from "./Home";
export { default as Login } from "./Login";
export { default as OrderConfirmed } from "./OrderConfirmed";
export { default as Orders } from "./Orders";
export { default as Register } from "./Register";
export { default as Shop } from "./Shop";
