export { default as About } from "./About/About";
export { default as Cart } from "./Cart/Cart";
export { default as Checkout } from "./Checkout/Checkout";
export { default as Home } from "./Home/Home";
export { default as Login } from "./Login/Login";
export { default as OrderConfirmed } from "./OrderConfirmed/OrderConfirmed";
export { default as Orders } from "./Orders/Orders";
export { default as Register } from "./Register/Register";
export { default as Shop } from "./Shop/Shop";
